using System; using Microsoft.EntityFrameworkCore.Migrations; using Microsoft.EntityFrameworkCore.Infrastructure; using DentalDashboard.Infrastracture.Context;
#nullable disable
namespace DentalDashboard.Infrastracture.Migrations;
[DbContext(typeof(DentalContext))]
[Migration("20260903120000_AddPatientReferralRewards")]
public partial class AddPatientReferralRewards:Migration { protected override void Up(MigrationBuilder m){
m.CreateTable("PatientReferrals",t=>new{Id=t.Column<long>(nullable:false).Annotation("SqlServer:Identity","1, 1"),ReferrerPatientUserId=t.Column<Guid>(nullable:false),ReferredFirstName=t.Column<string>(maxLength:100,nullable:false),ReferredLastName=t.Column<string>(maxLength:100,nullable:false),ReferredPhoneNumber=t.Column<string>(maxLength:11,nullable:false),Description=t.Column<string>(maxLength:500,nullable:true),Status=t.Column<int>(nullable:false),SecretaryUserId=t.Column<Guid>(nullable:true),ContactedAt=t.Column<DateTime>(nullable:true),LeadAssignmentId=t.Column<long>(nullable:true),ReservationId=t.Column<long>(nullable:true),RewardAmount=t.Column<decimal>(type:"decimal(18,2)",nullable:false),ReviewedByAdminId=t.Column<Guid>(nullable:true),ReviewedAt=t.Column<DateTime>(nullable:true),RejectionReason=t.Column<string>(maxLength:500,nullable:true),CreatedAt=t.Column<DateTime>(nullable:false),UpdatedAt=t.Column<DateTime>(nullable:true),IsDeleted=t.Column<bool>(nullable:false),DeletedAt=t.Column<DateTime>(nullable:true)},constraints:t=>{t.PrimaryKey("PK_PatientReferrals",x=>x.Id);t.ForeignKey("FK_PatientReferrals_Users_ReferrerPatientUserId",x=>x.ReferrerPatientUserId,"Users","Id",onDelete:ReferentialAction.Restrict);t.ForeignKey("FK_PatientReferrals_Users_SecretaryUserId",x=>x.SecretaryUserId,"Users","Id",onDelete:ReferentialAction.Restrict);t.ForeignKey("FK_PatientReferrals_Users_ReviewedByAdminId",x=>x.ReviewedByAdminId,"Users","Id",onDelete:ReferentialAction.Restrict);t.ForeignKey("FK_PatientReferrals_LeadAssignments_LeadAssignmentId",x=>x.LeadAssignmentId,"LeadAssignments","Id",onDelete:ReferentialAction.Restrict);t.ForeignKey("FK_PatientReferrals_Reservations_ReservationId",x=>x.ReservationId,"Reservations","Id",onDelete:ReferentialAction.Restrict);});
m.CreateTable("PatientWallets",t=>new{Id=t.Column<long>(nullable:false).Annotation("SqlServer:Identity","1, 1"),PatientUserId=t.Column<Guid>(nullable:false),Balance=t.Column<decimal>(type:"decimal(18,2)",nullable:false),CreatedAt=t.Column<DateTime>(nullable:false),UpdatedAt=t.Column<DateTime>(nullable:true),IsDeleted=t.Column<bool>(nullable:false),DeletedAt=t.Column<DateTime>(nullable:true)},constraints:t=>{t.PrimaryKey("PK_PatientWallets",x=>x.Id);t.CheckConstraint("CK_PatientWallets_Balance","[Balance] >= 0");t.ForeignKey("FK_PatientWallets_Users_PatientUserId",x=>x.PatientUserId,"Users","Id",onDelete:ReferentialAction.Restrict);});
m.CreateTable("PatientWalletTransactions",t=>new{Id=t.Column<long>(nullable:false).Annotation("SqlServer:Identity","1, 1"),WalletId=t.Column<long>(nullable:false),PatientUserId=t.Column<Guid>(nullable:false),PatientReferralId=t.Column<long>(nullable:false),Amount=t.Column<decimal>(type:"decimal(18,2)",nullable:false),TransactionType=t.Column<int>(nullable:false),Description=t.Column<string>(maxLength:500,nullable:false),CreatedAt=t.Column<DateTime>(nullable:false),UpdatedAt=t.Column<DateTime>(nullable:true),IsDeleted=t.Column<bool>(nullable:false),DeletedAt=t.Column<DateTime>(nullable:true)},constraints:t=>{t.PrimaryKey("PK_PatientWalletTransactions",x=>x.Id);t.CheckConstraint("CK_PatientWalletTransactions_Amount","[Amount] > 0");t.ForeignKey("FK_PatientWalletTransactions_PatientWallets_WalletId",x=>x.WalletId,"PatientWallets","Id",onDelete:ReferentialAction.Restrict);t.ForeignKey("FK_PatientWalletTransactions_Users_PatientUserId",x=>x.PatientUserId,"Users","Id",onDelete:ReferentialAction.Restrict);t.ForeignKey("FK_PatientWalletTransactions_PatientReferrals_PatientReferralId",x=>x.PatientReferralId,"PatientReferrals","Id",onDelete:ReferentialAction.Restrict);});
m.CreateIndex("IX_PatientReferrals_ReferrerPatientUserId_CreatedAt","PatientReferrals",new[]{"ReferrerPatientUserId","CreatedAt"});m.CreateIndex("IX_PatientReferrals_Status_CreatedAt","PatientReferrals",new[]{"Status","CreatedAt"});foreach(var c in new[]{"ReferredPhoneNumber","SecretaryUserId","ReviewedByAdminId","ReservationId","LeadAssignmentId"})m.CreateIndex("IX_PatientReferrals_"+c,"PatientReferrals",c);m.CreateIndex("IX_PatientWallets_PatientUserId","PatientWallets","PatientUserId",unique:true,filter:"[IsDeleted] = 0");m.CreateIndex("IX_PatientWalletTransactions_PatientUserId_CreatedAt","PatientWalletTransactions",new[]{"PatientUserId","CreatedAt"});m.CreateIndex("IX_PatientWalletTransactions_PatientReferralId_TransactionType","PatientWalletTransactions",new[]{"PatientReferralId","TransactionType"},unique:true);m.CreateIndex("IX_PatientWalletTransactions_WalletId","PatientWalletTransactions","WalletId");}
protected override void Down(MigrationBuilder m){m.DropTable("PatientWalletTransactions");m.DropTable("PatientWallets");m.DropTable("PatientReferrals");}}
