using DentalDashboard.ApplicationService.Contract.Requests.FollowUp.Commands;
using DentalDashboard.Domain.IRepositories;
using DentalDashboard.Framwork.Cqrs.Abstraction.Wrire;
using DentalDashboard.Framwork.Domain;
using Microsoft.EntityFrameworkCore;
namespace DentalDashboard.ApplicationService.Handlers.CommandHandlers.FollowUp;
public sealed class CreateSecretaryFollowUpCommandHandler(IReservationRepository reservations) : ICommandHandler<CreateSecretaryFollowUpCommand> { public async Task<Result> HandleAsync(CreateSecretaryFollowUpCommand c,CancellationToken ct=default){if(c.SecretaryUserId==Guid.Empty)return Result.Failure("کاربر جاری معتبر نیست");if(c.PatientId<=0)return Result.Failure("بیمار معتبر نیست");var result=c.ContactResult?.Trim();if(result?.Length>1000)return Result.Failure("نتیجه تماس نباید بیشتر از ۱۰۰۰ کاراکتر باشد");var r=await reservations.GetAll().Where(x=>!x.IsDeleted&&!x.IsCanceled&&x.LeadAssignmentId==c.PatientId).OrderByDescending(x=>x.ReservationAt).FirstOrDefaultAsync(ct);if(r==null)return Result.Failure("رزرو مرتبط یافت نشد");r.SecretaryFollowUpContacted=c.Contacted;r.SecretaryAnnouncement=string.IsNullOrWhiteSpace(result)?null:result;r.SecretaryAnnouncementUserId=c.SecretaryUserId;r.SecretaryAnnouncementUpdatedAt=DateTime.UtcNow;r.UpdatedAt=DateTime.UtcNow;reservations.Update(r);await reservations.SaveChange();return Result.Success("پیگیری با موفقیت ثبت شد");} }
public sealed class UpdateSecretaryFollowUpCommandHandler(IReservationRepository reservations) : ICommandHandler<UpdateSecretaryFollowUpCommand> { public async Task<Result> HandleAsync(UpdateSecretaryFollowUpCommand c,CancellationToken ct=default){if(c.Id<=0||c.SecretaryUserId==Guid.Empty)return Result.Failure("درخواست معتبر نیست");var result=c.ContactResult?.Trim();if(result?.Length>1000)return Result.Failure("نتیجه تماس نباید بیشتر از ۱۰۰۰ کاراکتر باشد");var r=await reservations.GetAll().FirstOrDefaultAsync(x=>!x.IsDeleted&&x.Id==c.Id&&x.SecretaryAnnouncementUserId==c.SecretaryUserId&&x.SecretaryAnnouncementUpdatedAt!=null,ct);if(r==null)return Result.Failure("پیگیری یافت نشد");r.SecretaryFollowUpContacted=c.Contacted;r.SecretaryAnnouncement=string.IsNullOrWhiteSpace(result)?null:result;r.SecretaryAnnouncementUpdatedAt=DateTime.UtcNow;r.UpdatedAt=DateTime.UtcNow;reservations.Update(r);await reservations.SaveChange();return Result.Success("پیگیری با موفقیت ویرایش شد");} }
public sealed class DeleteSecretaryFollowUpCommandHandler(IReservationRepository reservations) : ICommandHandler<DeleteSecretaryFollowUpCommand> { public async Task<Result> HandleAsync(DeleteSecretaryFollowUpCommand c,CancellationToken ct=default){if(c.Id<=0||c.SecretaryUserId==Guid.Empty)return Result.Failure("درخواست معتبر نیست");var r=await reservations.GetAll().FirstOrDefaultAsync(x=>!x.IsDeleted&&x.Id==c.Id&&x.SecretaryAnnouncementUserId==c.SecretaryUserId&&x.SecretaryAnnouncementUpdatedAt!=null,ct);if(r==null)return Result.Failure("پیگیری یافت نشد");r.SecretaryFollowUpContacted=null;r.SecretaryAnnouncement=null;r.SecretaryAnnouncementStatus=null;r.SecretaryAnnouncementUserId=null;r.SecretaryAnnouncementUpdatedAt=null;r.UpdatedAt=DateTime.UtcNow;reservations.Update(r);await reservations.SaveChange();return Result.Success("پیگیری با موفقیت حذف شد");} }
