<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentalDashboard.ApplicationService.Contract\DentalDashboard.ApplicationService.Contract.csproj" />
    <ProjectReference Include="..\DentalDashboard.Domain\DentalDashboard.Domain.csproj" />
    <ProjectReference Include="..\DentalDashboard.Framwork\DentalDashboard.Framwork.csproj" />
    <ProjectReference Include="..\DentalDashboard.Utilities\DentalDashboard.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Domain\**\*.cs" />
    <Compile Remove="Infrastructure\**\*.cs" />
    <Compile Remove="Integration\PatientFiles\Contracts\**\*.cs" />
  </ItemGroup>

</Project>
