using System.Data; using System.Security.Claims; using System.Text.RegularExpressions; using DentalDashboard.Domain.Enums; using DentalDashboard.Domain.Models; using DentalDashboard.Domain.PatientReferrals; using DentalDashboard.Infrastracture.Context; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace DentalDashboard.Controllers;
public record CreateReferralRequest(string FirstName,string LastName,string PhoneNumber,string? Description);
public record ReserveReferralRequest(long ConsultantProfileId,DateTime ReservationAt,string PatientCity,string PatientRegion,List<DentalServiceType> DentalServices,string? Description);
public record RejectReferralRequest(string Reason);
public sealed class ReferralFilters {public string? Search{get;set;} public PatientReferralStatus? Status{get;set;} public Guid? ReferrerPatientUserId{get;set;} public Guid? SecretaryUserId{get;set;} public DateTime? FromDate{get;set;} public DateTime? ToDate{get;set;} public int Page{get;set;}=1;public int PageSize{get;set;}=20;}
[ApiController] public sealed class PatientReferralsController(DentalContext db):ControllerBase {
 Guid UserId()=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirstValue("sub"),out var id)?id:Guid.Empty;
 async Task<bool> Valid(string role,CancellationToken ct)=>await db.Users.AnyAsync(x=>x.Id==UserId()&&x.IsActive&&!x.IsDeleted&&x.UserRoles.Any(r=>!r.IsDeleted&&!r.Role.IsDeleted&&r.Role.RoleName==role),ct);
 static object Page<T>(List<T> items,int total,int page,int size)=>new{items,total,page,pageSize=size,totalPages=(int)Math.Ceiling(total/(double)size)};
 [HttpPost("api/patient/referrals"),Authorize(Roles="Patient")]
 public async Task<IActionResult>Create(CreateReferralRequest r,CancellationToken ct){if(!await Valid("Patient",ct))return Forbid();var f=r.FirstName?.Trim()??"";var l=r.LastName?.Trim()??"";var p=r.PhoneNumber?.Trim()??"";var d=r.Description?.Trim();if(f.Length is <2 or >100||l.Length is <2 or >100||!Regex.IsMatch(p,"^09\\d{9}$")||d?.Length>500)return BadRequest("اطلاعات معرفی معتبر نیست.");var uid=UserId();if(await db.PatientReferrals.AnyAsync(x=>x.ReferrerPatientUserId==uid&&x.ReferredPhoneNumber==p&&x.Status!=PatientReferralStatus.Rejected,ct))return Conflict("این شماره قبلاً معرفی شده است.");var e=new PatientReferral{ReferrerPatientUserId=uid,ReferredFirstName=f,ReferredLastName=l,ReferredPhoneNumber=p,Description=d,RewardAmount=1_000_000m};db.Add(e);await db.SaveChangesAsync(ct);return Created($"/api/patient/referrals/{e.Id}",new{e.Id,e.Status,e.RewardAmount});}
 IQueryable<PatientReferral> Filter(ReferralFilters f){var q=db.PatientReferrals.AsNoTracking();if(f.Status.HasValue)q=q.Where(x=>x.Status==f.Status);if(f.ReferrerPatientUserId.HasValue)q=q.Where(x=>x.ReferrerPatientUserId==f.ReferrerPatientUserId);if(f.SecretaryUserId.HasValue)q=q.Where(x=>x.SecretaryUserId==f.SecretaryUserId);if(f.FromDate.HasValue)q=q.Where(x=>x.CreatedAt>=f.FromDate);if(f.ToDate.HasValue)q=q.Where(x=>x.CreatedAt<=f.ToDate);if(!string.IsNullOrWhiteSpace(f.Search)){var s=f.Search.Trim();q=q.Where(x=>(x.ReferrerPatientUser.FirstName+" "+x.ReferrerPatientUser.LastName).Contains(s)||(x.ReferredFirstName+" "+x.ReferredLastName).Contains(s)||x.ReferredPhoneNumber.Contains(s));}return q;}
 async Task<IActionResult> List(ReferralFilters f,IQueryable<PatientReferral> q,CancellationToken ct){f.Page=Math.Max(1,f.Page);f.PageSize=Math.Clamp(f.PageSize,1,100);var total=await q.CountAsync(ct);var rows=await q.OrderByDescending(x=>x.CreatedAt).Skip((f.Page-1)*f.PageSize).Take(f.PageSize).Select(x=>new{x.Id,x.ReferrerPatientUserId,ReferrerPatientName=x.ReferrerPatientUser.FirstName+" "+x.ReferrerPatientUser.LastName,x.ReferredFirstName,x.ReferredLastName,ReferredPatientName=x.ReferredFirstName+" "+x.ReferredLastName,x.ReferredPhoneNumber,x.Description,x.Status,x.RewardAmount,x.SecretaryUserId,SecretaryName=x.SecretaryUser==null?null:x.SecretaryUser.FirstName+" "+x.SecretaryUser.LastName,x.ContactedAt,x.ReservationId,ReservationAt=x.Reservation==null?(DateTime?)null:x.Reservation.ReservationAt,x.ReviewedAt,x.RejectionReason,x.CreatedAt}).ToListAsync(ct);return Ok(Page(rows,total,f.Page,f.PageSize));}
 [HttpGet("api/patient/referrals"),Authorize(Roles="Patient")]public async Task<IActionResult>PatientList([FromQuery]ReferralFilters f,CancellationToken ct)=>!await Valid("Patient",ct)?Forbid():await List(f,Filter(f).Where(x=>x.ReferrerPatientUserId==UserId()),ct);
 [HttpGet("api/secretary/patient-referrals"),Authorize(Roles="Secretary")]public async Task<IActionResult>SecretaryList([FromQuery]ReferralFilters f,CancellationToken ct)=>!await Valid("Secretary",ct)?Forbid():await List(f,Filter(f),ct);
 [HttpGet("api/admin/patient-referrals"),Authorize(Roles="Admin")]public async Task<IActionResult>AdminList([FromQuery]ReferralFilters f,CancellationToken ct)=>!await Valid("Admin",ct)?Forbid():await List(f,Filter(f),ct);
 [HttpPost("api/secretary/patient-referrals/{id:long}/contacted"),Authorize(Roles="Secretary")]public async Task<IActionResult>Contact(long id,CancellationToken ct){if(!await Valid("Secretary",ct))return Forbid();var e=await db.PatientReferrals.SingleOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(e.Status!=PatientReferralStatus.Submitted)return Conflict("فقط معرفی ثبت‌شده قابل تماس است.");e.Status=PatientReferralStatus.Contacted;e.SecretaryUserId=UserId();e.ContactedAt=e.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Ok();}
 [HttpGet("api/secretary/patient-referrals/consultants"),Authorize(Roles="Secretary")]public async Task<IActionResult>Consultants(CancellationToken ct){if(!await Valid("Secretary",ct))return Forbid();return Ok(await db.ConsultantProfiles.AsNoTracking().Where(x=>!x.IsDeleted&&x.IsCompleteProfile&&!x.User.IsDeleted&&x.User.IsActive).Select(x=>new{x.ConsultantProfileId=x.Id,FullName=x.User.FirstName+" "+x.User.LastName,x.User.PhoneNumber}).ToListAsync(ct));}
 [HttpPost("api/secretary/patient-referrals/{id:long}/reserve"),Authorize(Roles="Secretary")]
 public async Task<IActionResult>Reserve(long id,ReserveReferralRequest r,CancellationToken ct){if(!await Valid("Secretary",ct))return Forbid();if(r.ReservationAt<=DateTime.UtcNow||string.IsNullOrWhiteSpace(r.PatientCity)||string.IsNullOrWhiteSpace(r.PatientRegion)||r.DentalServices?.Distinct().Any()!=true)return BadRequest("اطلاعات رزرو معتبر نیست.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var e=await db.PatientReferrals.SingleOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(e.Status!=PatientReferralStatus.Contacted||e.ReservationId!=null||e.LeadAssignmentId!=null)return Conflict("معرفی قابل رزرو نیست.");var c=await db.ConsultantProfiles.Include(x=>x.User).SingleOrDefaultAsync(x=>x.Id==r.ConsultantProfileId&&!x.IsDeleted&&x.IsCompleteProfile&&x.User.IsActive&&!x.User.IsDeleted,ct);if(c is null)return BadRequest("مشاور معتبر نیست.");if(c.LimitNumber.HasValue&&await db.Reservations.CountAsync(x=>!x.IsDeleted&&!x.IsCanceled&&x.ConsultantProfileId==c.Id&&x.ReservationAt==r.ReservationAt,ct)>=c.LimitNumber)return Conflict("ظرفیت تکمیل است.");var now=DateTime.UtcNow;var lead=new LeadAssignment{UserName=$"{e.ReferredFirstName} {e.ReferredLastName}",PhoneNumber=e.ReferredPhoneNumber,ConsultantProfileId=c.Id,PatientCity=r.PatientCity.Trim(),PatientRegion=r.PatientRegion.Trim(),AssignmentType=LeadAssignmentType.ConsultantPatient,LeadAssignmentState=LeadAssignmentState.Converted,CallResult=LeadCallResult.Converted,ReportSubmittedAt=now,ContactedAt=e.ContactedAt,AssignedAt=now};db.Add(lead);await db.SaveChangesAsync(ct);var reservation=new Reservation{LeadAssignmentId=lead.Id,ConsultantProfileId=c.Id,ReservationAt=r.ReservationAt,DentalServices=r.DentalServices.Distinct().ToList(),Description=r.Description?.Trim(),OwnerType=ReservationOwnerType.Secretary,OwnerUserId=UserId(),SecretaryUserId=UserId(),InitialReservationAt=r.ReservationAt,LastActivityAt=now};db.Add(reservation);await db.SaveChangesAsync(ct);e.LeadAssignmentId=lead.Id;e.ReservationId=reservation.Id;e.SecretaryUserId=UserId();e.Status=PatientReferralStatus.ReservedPendingAdminApproval;e.UpdatedAt=now;await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Ok(new{e.Id,e.Status,e.ReservationId,e.LeadAssignmentId});}
 [HttpPost("api/admin/patient-referrals/{id:long}/approve"),Authorize(Roles="Admin")]public async Task<IActionResult>Approve(long id,CancellationToken ct){if(!await Valid("Admin",ct))return Forbid();await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var e=await db.PatientReferrals.SingleOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(e.Status!=PatientReferralStatus.ReservedPendingAdminApproval||e.ReservationId is null)return Conflict("معرفی قابل تأیید نیست.");if(!await db.Reservations.AnyAsync(x=>x.Id==e.ReservationId&&!x.IsDeleted&&!x.IsCanceled,ct))return Conflict("رزرو فعال نیست.");if(await db.PatientWalletTransactions.AnyAsync(x=>x.PatientReferralId==id&&x.TransactionType==PatientWalletTransactionType.ReferralReward,ct))return Conflict("پاداش قبلاً پرداخت شده است.");var wallet=await db.PatientWallets.SingleOrDefaultAsync(x=>x.PatientUserId==e.ReferrerPatientUserId,ct);if(wallet is null){wallet=new PatientWallet{PatientUserId=e.ReferrerPatientUserId};db.Add(wallet);await db.SaveChangesAsync(ct);}var now=DateTime.UtcNow;wallet.Balance+=e.RewardAmount;wallet.UpdatedAt=now;db.Add(new PatientWalletTransaction{WalletId=wallet.Id,PatientUserId=e.ReferrerPatientUserId,PatientReferralId=e.Id,Amount=e.RewardAmount,TransactionType=PatientWalletTransactionType.ReferralReward,Description=$"پاداش معرفی بیمار {e.ReferredFirstName} {e.ReferredLastName}"});e.Status=PatientReferralStatus.ApprovedRewarded;e.ReviewedByAdminId=UserId();e.ReviewedAt=e.UpdatedAt=now;try{await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}catch(DbUpdateException){await tx.RollbackAsync(ct);return Conflict("پاداش قبلاً پرداخت شده است.");}return Ok(new{e.Status,wallet.Balance});}
 [HttpPost("api/admin/patient-referrals/{id:long}/reject"),Authorize(Roles="Admin")]public async Task<IActionResult>Reject(long id,RejectReferralRequest r,CancellationToken ct){if(!await Valid("Admin",ct))return Forbid();var reason=r.Reason?.Trim()??"";if(reason.Length is <1 or >500)return BadRequest("دلیل رد الزامی و حداکثر ۵۰۰ نویسه است.");var e=await db.PatientReferrals.SingleOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(e.Status!=PatientReferralStatus.ReservedPendingAdminApproval)return Conflict("معرفی قابل رد نیست.");e.Status=PatientReferralStatus.Rejected;e.RejectionReason=reason;e.ReviewedByAdminId=UserId();e.ReviewedAt=e.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Ok();}
 [HttpGet("api/patient/referrals/dashboard"),Authorize(Roles="Patient")]public async Task<IActionResult>Dashboard(CancellationToken ct){if(!await Valid("Patient",ct))return Forbid();var uid=UserId();var u=await db.Users.AsNoTracking().SingleAsync(x=>x.Id==uid,ct);var q=db.PatientReferrals.AsNoTracking().Where(x=>x.ReferrerPatientUserId==uid);return Ok(new{u.FirstName,u.LastName,WalletBalance=await db.PatientWallets.Where(x=>x.PatientUserId==uid).Select(x=>(decimal?)x.Balance).SingleOrDefaultAsync(ct)??0,TotalReferrals=await q.CountAsync(ct),PendingReferrals=await q.CountAsync(x=>x.Status==PatientReferralStatus.Submitted||x.Status==PatientReferralStatus.Contacted||x.Status==PatientReferralStatus.ReservedPendingAdminApproval,ct),ApprovedReferrals=await q.CountAsync(x=>x.Status==PatientReferralStatus.ApprovedRewarded,ct),RejectedReferrals=await q.CountAsync(x=>x.Status==PatientReferralStatus.Rejected,ct),RecentReferrals=await q.OrderByDescending(x=>x.CreatedAt).Take(10).Select(x=>new{x.Id,x.ReferredFirstName,x.ReferredLastName,x.Status,x.CreatedAt}).ToListAsync(ct)});}
 [HttpGet("api/patient/referrals/wallet/transactions"),Authorize(Roles="Patient")]public async Task<IActionResult>Transactions([FromQuery]PatientWalletTransactionType? transactionType,[FromQuery]DateTime? fromDate,[FromQuery]DateTime? toDate,[FromQuery]int page=1,[FromQuery]int pageSize=20,CancellationToken ct=default){if(!await Valid("Patient",ct))return Forbid();page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var uid=UserId();var q=db.PatientWalletTransactions.AsNoTracking().Where(x=>x.PatientUserId==uid);if(transactionType.HasValue)q=q.Where(x=>x.TransactionType==transactionType);if(fromDate.HasValue)q=q.Where(x=>x.CreatedAt>=fromDate);if(toDate.HasValue)q=q.Where(x=>x.CreatedAt<=toDate);var total=await q.CountAsync(ct);var rows=await q.OrderByDescending(x=>x.CreatedAt).Skip((page-1)*pageSize).Take(pageSize).Select(x=>new{x.TransactionId=x.Id,x.Amount,x.TransactionType,x.Description,x.CreatedAt,x.PatientReferralId,ReferredPatientName=x.PatientReferral.ReferredFirstName+" "+x.PatientReferral.ReferredLastName}).ToListAsync(ct);return Ok(Page(rows,total,page,pageSize));}
}
